name: prettier

on:
  push:
    branches:
      - master
      - beta1
  pull_request:
    branches:
      - master
      - beta1

env:
  FILE_PATTERN: "src/**/*.{ts,tsx,js,jsx}"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Run Prettier
        run: yarn install --frozen-lockfile && yarn style
      - uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: Apply Prettier Change
